{ lib, buildGoModule, fetchFromGitHub, installShellFiles }:

buildGoModule rec {
  pname = "fastmail-cli";
  version = "0.7.0";

  src = fetchFromGitHub {
    owner = "vicyap";
    repo = "fastmail-cli";
    rev = "refs/tags/v${version}";
    hash = "sha256-tZxIhH8TMdp+xd3VnQ84593OsGZt6Ip0S9XXzmAUoo4=";
  };

  vendorHash = "sha256-VyuGiqyzgmp6CeGwnQnkvzTztnO+l2RKlrLVuS/N2F0=";

  # Build both the main binary and the gendocs tool used for man page
  # generation. The gendocs binary is removed from the output below.
  subPackages = [ "." "cmd/gendocs" ];

  nativeBuildInputs = [ installShellFiles ];

  ldflags = [
    "-s"
    "-w"
    "-X github.com/vicyap/fastmail-cli/cmd.Version=${version}"
  ];

  # Tests that require a mock server need network access. Unit tests pass
  # but some test keyring behavior that's incompatible with the sandbox.
  doCheck = false;

  postInstall = ''
    # The main binary is named after the Go module; rename to the expected "fm"
    mv $out/bin/fastmail-cli $out/bin/fm

    # Shell completions
    $out/bin/fm completion bash > fm.bash
    $out/bin/fm completion zsh > _fm
    $out/bin/fm completion fish > fm.fish
    installShellCompletion --bash fm.bash --zsh _fm --fish fm.fish

    # Man pages (generated by the gendocs tool we built alongside fm)
    mkdir -p man
    $out/bin/gendocs man man
    installManPage man/*.1

    # Agent skills
    mkdir -p $out/share/fastmail-cli/agents/skills/fastmail
    cp -r ${src}/.agents/skills/fastmail/* $out/share/fastmail-cli/agents/skills/fastmail/

    # Remove the gendocs tool — it's only needed for man page generation
    rm $out/bin/gendocs
  '';

  meta = with lib; {
    description = "Command-line interface for Fastmail using JMAP";
    homepage = "https://github.com/vicyap/fastmail-cli";
    license = licenses.mit;
    mainProgram = "fm";
    platforms = platforms.unix;
  };
}
